import type { LucideIcon } from "lucide-react";
import {
  Binary,
  Braces,
  Brain,
  CalendarClock,
  Calculator,
  CaseSensitive,
  CircleDot,
  Clock,
  Coins,
  Contrast,
  Database,
  Dice6,
  FileText,
  GitCompare,
  Globe,
  Hash,
  KeyRound,
  Layers,
  Lightbulb,
  Link,
  Link2,
  Lock,
  MapPin,
  Paintbrush,
  Palette,
  Pilcrow,
  Pipette,
  QrCode,
  Regex,
  Ruler,
  ShieldCheck,
  Smile,
  Table,
  Timer,
  Type,
  WholeWord,
} from "lucide-react";

export const NAV_IDS = [
  "palette",
  "markdown",
  "inspo",
  "json",
  "regex",
  "timestamp",
  "contrast",
  "generator",
  "base64",
  "url",
  "lorem",
  "hash",
  "wordcount",
  "cssunit",
  "slug",
  "textcase",
  "csvjson",
  "httpstatus",
  "cron",
  "qrcode",
  "jwt",
  "pomodoro",
  "ipinfo",
  "diff",
  "baseconv",
  "gradient",
  "password",
  "eightball",
  "coinflip",
  "dice",
  "ascii",
  "colorgame",
  "sql",
  "emoji",
  "shadow",
] as const;

export type ToolId = (typeof NAV_IDS)[number];

export interface ToolMeta {
  cat: string;
  keywords: string;
  label: string;
  desc: string;
  icon: LucideIcon;
}

export const TOOL_META: Record<ToolId, ToolMeta> = {
  palette: { cat: "Design", keywords: "color palette hsl css design", label: "Color Palette", desc: "Generate a palette, randomize a colorway, copy CSS-ready values.", icon: Palette },
  markdown: { cat: "Text", keywords: "markdown preview convert text", label: "Markdown Preview", desc: "Live preview for headings, bold, italics, and lists.", icon: FileText },
  inspo: { cat: "Fun", keywords: "inspiration quote random motivational", label: "Inspiration", desc: "Quick idea spark when you're stuck.", icon: Lightbulb },
  json: { cat: "Code", keywords: "json format validate pretty print", label: "JSON Formatter", desc: "Validate, prettify, or minify JSON.", icon: Braces },
  regex: { cat: "Code", keywords: "regex regular expression test match", label: "Regex Tester", desc: "Test JavaScript regexes against live input.", icon: Regex },
  timestamp: { cat: "Convert", keywords: "timestamp unix date time convert", label: "Timestamp Converter", desc: "Unix ↔ human-readable, both directions.", icon: Clock },
  contrast: { cat: "Design", keywords: "contrast wcag accessibility color", label: "Contrast Checker", desc: "WCAG accessibility contrast ratios.", icon: Contrast },
  generator: { cat: "Code", keywords: "uuid generate random id", label: "Generator Kit", desc: "UUID v4 and secure password generation.", icon: KeyRound },
  base64: { cat: "Encode", keywords: "base64 encode decode binary text", label: "Base64", desc: "Encode or decode Base64 strings.", icon: Binary },
  url: { cat: "Encode", keywords: "url encode decode uri component", label: "URL Encoder", desc: "Encode or decode URL components.", icon: Link2 },
  lorem: { cat: "Text", keywords: "lorem ipsum placeholder dummy text", label: "Lorem Ipsum", desc: "Generate placeholder text by the paragraph.", icon: Pilcrow },
  hash: { cat: "Encode", keywords: "hash md5 sha1 sha256 digest", label: "Hash Generator", desc: "SHA-1 / 256 / 384 / 512 digests.", icon: Hash },
  wordcount: { cat: "Text", keywords: "word count character line text", label: "Word Counter", desc: "Live word, character, and reading-time stats.", icon: WholeWord },
  cssunit: { cat: "Design", keywords: "css unit convert px rem em vh", label: "CSS Unit Converter", desc: "px, rem, em, pt, vw, vh — converted live.", icon: Ruler },
  slug: { cat: "Text", keywords: "slug generator kebab case seo permalink url", label: "Slug Studio", desc: "Clean SEO slugs, URL paths, snake_case handles.", icon: Link },
  textcase: { cat: "Text", keywords: "text case uppercase lowercase title sentence camel pascal", label: "Text Case Studio", desc: "Title, sentence, camel, Pascal, kebab, snake.", icon: CaseSensitive },
  csvjson: { cat: "Convert", keywords: "csv json converter parse data table rows columns", label: "CSV ↔ JSON", desc: "Flat CSV rows to JSON objects and back.", icon: Table },
  httpstatus: { cat: "Code", keywords: "http status code api response error reference", label: "HTTP Status Explorer", desc: "The response codes you half-remember mid-debug.", icon: Globe },
  cron: { cat: "Code", keywords: "cron builder schedule expression devops timer", label: "Cron Builder", desc: "Five-field cron with presets and plain English.", icon: CalendarClock },
  qrcode: { cat: "Fun", keywords: "qr code generate scan url", label: "QR Code Generator", desc: "Branded QR codes with custom size and colors.", icon: QrCode },
  jwt: { cat: "Code", keywords: "jwt json web token decode header", label: "JWT Decoder", desc: "Decode payloads, inspect claims, spot expiry.", icon: ShieldCheck },
  pomodoro: { cat: "Fun", keywords: "pomodoro timer focus productivity", label: "Pomodoro Timer", desc: "Focus presets with round tracking.", icon: Timer },
  ipinfo: { cat: "Convert", keywords: "ip address geolocation info lookup", label: "IP Address Info", desc: "Your public IP and geolocation details.", icon: MapPin },
  diff: { cat: "Code", keywords: "diff compare text changes check", label: "Diff Checker", desc: "Compare two texts side by side.", icon: GitCompare },
  baseconv: { cat: "Convert", keywords: "base convert binary hex octal decimal", label: "Base Converter", desc: "Decimal, binary, octal, and hex.", icon: Calculator },
  gradient: { cat: "Design", keywords: "gradient css color generate linear", label: "Gradient Generator", desc: "Create and copy CSS gradients.", icon: Paintbrush },
  password: { cat: "Encode", keywords: "password strength test secure checker", label: "Password Strength", desc: "Test strength and get security tips.", icon: Lock },
  eightball: { cat: "Fun", keywords: "magic 8 ball random answer shake", label: "Magic 8-Ball", desc: "Ask a question, shake for answers.", icon: CircleDot },
  coinflip: { cat: "Fun", keywords: "coin flip heads tails 3d animation", label: "Coin Flip", desc: "3D animated coin with streak tracker.", icon: Coins },
  dice: { cat: "Fun", keywords: "dice roller d6 roll random numbers", label: "Dice Roller", desc: "Roll 1–6 dice with sum and history.", icon: Dice6 },
  ascii: { cat: "Fun", keywords: "ascii art text convert block letters", label: "ASCII Art", desc: "Text to large ASCII block letters.", icon: Type },
  colorgame: { cat: "Fun", keywords: "color game matching guess puzzle", label: "Color Guessing Game", desc: "Match the hex to the right square.", icon: Pipette },
  sql: { cat: "Code", keywords: "sql formatter pretty print query indent keywords database", label: "SQL Formatter", desc: "Indented, uppercased, clause-broken SQL.", icon: Database },
  emoji: { cat: "Text", keywords: "emoji unicode picker symbol arrow check copy search", label: "Emoji & Symbols", desc: "Search and click to copy — emoji, arrows, math.", icon: Smile },
  shadow: { cat: "Design", keywords: "box shadow generator css layer depth drop shadow design", label: "Box Shadow", desc: "Multi-layer box-shadow with live preview.", icon: Layers },
};

export const CATEGORIES = ["All", "Code", "Encode", "Design", "Text", "Convert", "Fun"] as const;

export const CAT_COLORS: Record<(typeof CATEGORIES)[number], string> = {
  All: "#06b6d4",
  Code: "#a855f7",
  Encode: "#f59e0b",
  Design: "#ec4899",
  Text: "#10b981",
  Convert: "#3b82f6",
  Fun: "#ef4444",
};
