export const NAV_IDS = [
  "palette",
  "markdown",
  "inspo",
  "json",
  "regex",
  "timestamp",
  "contrast",
  "generator",
  "base64",
  "url",
  "lorem",
  "hash",
  "wordcount",
  "cssunit",
  "slug",
  "textcase",
  "csvjson",
  "httpstatus",
  "cron",
  "qrcode",
  "jwt",
  "pomodoro",
  "ipinfo",
  "diff",
  "baseconv",
  "gradient",
  "password",
  "eightball",
  "coinflip",
  "dice",
  "ascii",
  "colorgame",
] as const;

export type ToolId = (typeof NAV_IDS)[number];

export const TOOL_META: Record<ToolId, { cat: string; keywords: string }> = {
  palette: { cat: "Design", keywords: "color palette hsl css design" },
  markdown: { cat: "Text", keywords: "markdown preview convert text" },
  inspo: { cat: "Fun", keywords: "inspiration quote random motivational" },
  json: { cat: "Code", keywords: "json format validate pretty print" },
  regex: { cat: "Code", keywords: "regex regular expression test match" },
  timestamp: { cat: "Convert", keywords: "timestamp unix date time convert" },
  contrast: { cat: "Design", keywords: "contrast wcag accessibility color" },
  generator: { cat: "Code", keywords: "uuid generate random id" },
  base64: { cat: "Encode", keywords: "base64 encode decode binary text" },
  url: { cat: "Encode", keywords: "url encode decode uri component" },
  lorem: { cat: "Text", keywords: "lorem ipsum placeholder dummy text" },
  hash: { cat: "Encode", keywords: "hash md5 sha1 sha256 digest" },
  wordcount: { cat: "Text", keywords: "word count character line text" },
  cssunit: { cat: "Design", keywords: "css unit convert px rem em vh" },
  slug: { cat: "Text", keywords: "slug generator kebab case seo permalink url" },
  textcase: { cat: "Text", keywords: "text case uppercase lowercase title sentence camel pascal" },
  csvjson: { cat: "Convert", keywords: "csv json converter parse data table rows columns" },
  httpstatus: { cat: "Code", keywords: "http status code api response error reference" },
  cron: { cat: "Code", keywords: "cron builder schedule expression devops timer" },
  qrcode: { cat: "Fun", keywords: "qr code generate scan url" },
  jwt: { cat: "Code", keywords: "jwt json web token decode header" },
  pomodoro: { cat: "Fun", keywords: "pomodoro timer focus productivity" },
  ipinfo: { cat: "Convert", keywords: "ip address geolocation info lookup" },
  diff: { cat: "Code", keywords: "diff compare text changes check" },
  baseconv: { cat: "Convert", keywords: "base convert binary hex octal decimal" },
  gradient: { cat: "Design", keywords: "gradient css color generate linear" },
  password: { cat: "Encode", keywords: "password strength test secure checker" },
  eightball: { cat: "Fun", keywords: "magic 8 ball random answer shake" },
  coinflip: { cat: "Fun", keywords: "coin flip heads tails 3d animation" },
  dice: { cat: "Fun", keywords: "dice roller d6 roll random numbers" },
  ascii: { cat: "Fun", keywords: "ascii art text convert block letters" },
  colorgame: { cat: "Fun", keywords: "color game matching guess puzzle" },
};

export const CATEGORIES = ["All", "Code", "Encode", "Design", "Text", "Convert", "Fun"] as const;

export const CAT_COLORS: Record<(typeof CATEGORIES)[number], string> = {
  All: "#06b6d4",
  Code: "#a855f7",
  Encode: "#f59e0b",
  Design: "#ec4899",
  Text: "#10b981",
  Convert: "#3b82f6",
  Fun: "#ef4444",
};
